config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories do 
  resources :payments
  end
  root "home#index"
  get 'about_us', to: 'home#about_us'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    return unless user.present?

    can :manage, Category, user_id: user.id
    can :manage, Payment, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :payments

  validates :name, presence: true, length: { maximum: 50 }
  validates :icon, presence: true
  def total_transaction_amount
    payments.sum(:amount)
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :category

  validates :name, presence: true, length: { maximum: 50 }
  validates :amount, presence: true, numericality: { greater_than: 0, only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :categories
  has_many :payments, foreign_key: :author_id
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(_resource)
    categories_path # Redirect to the categories page
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  def index
    @categories = Category.includes(:payments).where(user_id: current_user.id).order(updated_at: :desc)
  end

  def show
    @category = Category.find_by_id(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render 'new'
    end
  end

  private

  def category_params
    params[:category].merge!(user_id: current_user.id.to_s)
    params.require(:category).permit(:icon, :name, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def about_us; end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!
  def index
    @category = Category.find(params[:category_id])
    @payments = Payment.where(author: current_user, category_id: @category.id).order(updated_at: :desc)
    @total = Payment.where(author: current_user, category_id: @category.id).sum(:amount)
  end

  def new
    @payment = Payment.new
  end

  def create
    @payment = Payment.new(payment_params)
    @payment.author_id = current_user.id
    category = Category.find(params[:category_id])
    @payment.category_id = category.id
    if @payment.save
      redirect_to category_payments_path
    else
      render 'new'
    end
  end

  private

  def payment_params
    params.require(:payment).permit(:name, :amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/categories/index.html.erb
<% if @categories.empty?%>
    <h1>Hello, currently you don't have any categories to choose from. You can create a new Category with by clicking
    the button bellow.
    </h1>
<%else%>
<div class="parent-cat">
 <% @categories.each do |category|%>
   <a href="<%= category_payments_path(category.id) %>" class="children-cat">       
            <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 576 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M547.6 103.8L490.3 13.1C485.2 5 476.1 0 466.4 0H109.6C99.9 0 90.8 5 85.7 13.1L28.3 103.8c-29.6 46.8-3.4 111.9 51.9 119.4c4 .5 8.1 .8 12.1 .8c26.1 0 49.3-11.4 65.2-29c15.9 17.6 39.1 29 65.2 29c26.1 0 49.3-11.4 65.2-29c15.9 17.6 39.1 29 65.2 29c26.2 0 49.3-11.4 65.2-29c16 17.6 39.1 29 65.2 29c4.1 0 8.1-.3 12.1-.8c55.5-7.4 81.8-72.5 52.1-119.4zM499.7 254.9l-.1 0c-5.3 .7-10.7 1.1-16.2 1.1c-12.4 0-24.3-1.9-35.4-5.3V384H128V250.6c-11.2 3.5-23.2 5.4-35.6 5.4c-5.5 0-11-.4-16.3-1.1l-.1 0c-4.1-.6-8.1-1.3-12-2.3V384v64c0 35.3 28.7 64 64 64H448c35.3 0 64-28.7 64-64V384 252.6c-4 1-8 1.8-12.3 2.3z"/></svg>
            <p><%= category.name%></p>
            <strong><p>$<%= category.total_transaction_amount%></p></strong>
    <a/>
</div>
<%end%>
<%end%>
<div class="cat-btn">
    <%= link_to "Create a New Category", new_category_path, class: "btn bg-primary", style:"color: white"%>
</div>

app/views/categories/new.html.erb
<h1>Create a New Category</h1>
<%= form_with model: @category do |form|%>  
<div>
    <div class="sign-up">
        <%= form.text_field :icon , placeholder: "Enter Icon Link"%>
    </div>
     <div class="sign-up">
        <%= form.text_field :name , placeholder: "Enter a Name"%>
    </div>
    <div>
        <%= form.submit%>
    </div>
<%end%>
</div>

app/views/categories/show.html.erb
<h1>Hello Show Categories</h1>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-primary " data-bs-theme="dark"  >
  <div class="container-fluid">
    <%= link_to "SnapScan", root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to "About Us", about_us_path, class:"nav-link active"%>
        <%= link_to "Categories", categories_path, class:"nav-link active"%>
         <% if user_signed_in? %>
         <%= button_to "Sign Out", destroy_user_session_path,  method: :delete, class: 'nav-link' %>
                <% else %>
                <%= link_to "Sign In", new_user_session_path ,class:"nav-link"%>
            <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/home/about_us.html.erb
<div class="about-us">
    <p class="abt-des">SnapScan is a mobile application specially crafted to let the user have a count of their expanses. 
    It provides the user with security and an impressive UI/UX. This app is built with Ruby On Rails.</p>
</div>
<footer>
        <p>&copy; 2023 SnapScan</p>
        <p>Crafted by <a href="https://github.com/IsmailChangezi">Ismail Changezi</a></p>
</footer>

app/views/home/index.html.erb
<section class="bold main-text">SnapScan</section>

<section class="login-btns container">
    <%= button_to "LOG IN" , new_user_session_path, class: "login-btn" %>
    <br/>
    <%= link_to "SIGN UP" , new_user_registration_path, class: "btn btn-primary" %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SnapScan</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>

  <body>
      <%= render "home/header"%>
      <br/>
   <main class="container">
      <%= yield %>
      <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    </main>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</html>

app/views/payments/index.html.erb
<div class="header reg-head">
<a href="<%= categories_path %>">
  <i class="fa-solid fa-arrow-left"></i>
  </a>
  <p>TRANSACTIONS</p>
  <a href="/logout" data-method="delete">
 <i class="fa-solid fa-arrow-right-from-bracket"></i>
  </a>
</div>

<div id="payments">

<% if @payments.empty? %>
      <div class="empty-message">There are no Transactions for this category. Add one by clicking the button below.</div>
    <% else %>
  <% @payments.each do |payment| %>
  <div class="single-payment">
      <p class="payment-name"><%= payment.name %></p>
      <p> $ <%= payment.amount %> </p>
    </div>
  <% end %>
  <% end %>

 <div class="green-btn">
    <%= link_to "NEW TRANSACTION", new_category_payment_path %>
  </div>

</div>

app/views/payments/new.html.erb
<%= form_with(model: @payment, url: category_payments_path) do |form| %>
<div class="header reg-head">
<a href="<%= category_payments_path %>">
  <i class="fa-solid fa-arrow-left"></i>
  </a>
  <p>NEW TRANSACTION</p>
  
</div>
<div class="form-container sign-up">

    <%= form.text_field :name, placeholder: "Name" %>

    <%= form.text_field :amount, placeholder: "Amount" %>

  </div>
    <%= form.submit "Create", class: "reg-next" %>
<% end %>